# Generated by Django 2.2.3 on 2023-09-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opinion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
